image: python:3.9-slim

code-review:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    - if: '$CI_MERGE_REQUEST_EVENT_TYPE =~ /^(open|reopen|update)$/'
      when: always
    - if: '$CI_MERGE_REQUEST_EVENT_TYPE == "approved"'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_comment"'
      when: always
  script:
#    - export VERSION=5.rc-1
#    - apt-get update
#    - apt-get install curl -y
#    - apt-get install zip unzip -y
#    - curl -L https://github.com/utsmannn/corivai/archive/refs/tags/v${VERSION}.zip -o action_code.zip
#    - unzip action_code.zip
#    - cp -R corivai-${VERSION}/corivai .
#    - cp corivai-${VERSION}/requirements.txt .
    - pip install -r requirements.txt
    - python -m corivai.main-gitlab
  variables:
    API_KEY: '$REVIEWER_API_KEY'
    INPUT_OPENAI-URL: "https://generativelanguage.googleapis.com/v1beta/openai/"
    INPUT_MAX_DIFF_SIZE: "500000"
    INPUT_MODEL_NAME: "gemini-1.5-flash"