image: python:3.9-slim

code-review:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    - if: '$CI_MERGE_REQUEST_EVENT_TYPE =~ /^(open|reopen|update)$/'
      when: always
    - if: '$CI_MERGE_REQUEST_EVENT_TYPE == "approved"'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_comment"'
      when: always
  script:
    - apt install curl -y
    - curl -L https://github.com/utsmannn/corivai/archive/refs/tags/v4.zip -o action_code.zip
    - unzip action_code.zip
    - cp -R corivai-main/src .
    - cp corivai-main/requirements.txt .
    - pip install -r requirements.txt
    - python -m src.main-gitlab
  variables:
    REVIEWER_OPENAI_URL: "https://generativelanguage.googleapis.com/v1beta/openai/"
    REVIEWER_MAX_DIFF_SIZE: "500000"
    REVIEWER_MODEL_NAME: "gemini-1.5-flash"