name: 'Corivai - Code Review AI Assistant'
description: 'AI-powered code review with custom instructions'
inputs:
  reviewer-api-key:
    description: 'Provider API Key'
    required: true
  github-token:
    description: 'GitHub Token'
    required: true
  model-name:
    description: 'Gemini model name'
    required: true
    default: ''
  open-ai-url:
    description: 'End point for OpenAI library compatibility'
    required: true
    default: ''
  custom-instructions:
    description: 'Additional review instructions (Markdown supported)'
    required: false
    default: ''
  max-diff-size:
    description: 'Max size of diff for analysts'
    required: false
    default: '100000'

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install requests
      shell: bash

    - name: Execute review
      env:
        API_KEY: ${{ inputs.reviewer-api-key }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
        INPUT_OPEN-AI-URL: ${{ inputs.open-ai-url }}
        INPUT_MODEL-NAME: ${{ inputs.model-name }}
        INPUT_CUSTOM-INSTRUCTIONS: ${{ inputs.custom-instructions }}
        INPUT_MAX_DIFF_SIZE: ${{ inputs.max-diff-size }}
      run: python -m src.main
      shell: bash

    - name: Track Comments
      if: inputs.issue-number != ''
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        ISSUE_NUMBER: ${{ inputs.issue-number }}
        REPO: ${{ github.repository }}
      run: python -m src.comment_tracker
      shell: bash