name: 'Corivai - Code Review AI Assistant'
description: 'AI-powered code review with custom instructions'
author: Muhammad Utsman
branding:
  icon: "activity"
  color: "red"
inputs:
  reviewer-api-key:
    description: 'Provider API Key'
    required: true
  github-token:
    description: 'GitHub Token'
    required: true
  model-name:
    description: 'Gemini model name'
    required: true
    default: ''
  openai-url:
    description: 'Endpoint for OpenAI library compatibility'
    required: false
    default: 'https://api.openai.com/v1'
  custom-instructions:
    description: 'Additional review instructions (Markdown supported)'
    required: false
    default: ''
  max-diff-size:
    description: 'Max size of diff for analysts'
    required: false
    default: '100000'

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install requests
      shell: bash

    - name: Execute review
      if: github.event_name == 'pull_request'
      env:
        API_KEY: ${{ inputs.reviewer-api-key }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
        INPUT_OPENAI-URL: ${{ inputs.openai-url }}
        INPUT_MODEL-NAME: ${{ inputs.model-name }}
        INPUT_CUSTOM-INSTRUCTIONS: ${{ inputs.custom-instructions }}
        INPUT_MAX_DIFF_SIZE: ${{ inputs.max-diff-size }}
      run: python -m src.main
      shell: bash

    - name: Process Review Comments
      if: github.event_name == 'pull_request_review_comment'
      env:
        API_KEY: ${{ inputs.reviewer-api-key }}
        INPUT_OPENAI-URL: ${{ inputs.openai-url }}
        INPUT_MODEL-NAME: ${{ inputs.model-name }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
        COMMENT_BODY: ${{ github.event.comment.body }}
        COMMENT_ID: ${{ github.event.comment.id }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        REPO: ${{ github.repository }}
        REVIEW_THREAD_ID: ${{ github.event.comment.pull_request_review_id }}
        USER_LOGIN: ${{ github.event.comment.user.login }}
      run: python -m src.comment_processor
      shell: bash