image: python:3.9-slim

code-review:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    - if: '$CI_MERGE_REQUEST_EVENT_TYPE =~ /^(open|reopen|update)$/'
      when: always
    - if: '$CI_MERGE_REQUEST_EVENT_TYPE == "approved"'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_comment"'
      when: always
  script:
    - pip install -r requirements.txt
    - python main-gitlab.py
  variables:
    openai-url: https://generativelanguage.googleapis.com/v1beta/openai/
    max-diff-size: 500000
    model-name: gemini-1.5-flash