name: Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created]

jobs:
  track_comments:
    if: |
      github.event_name == 'issue_comment'
    runs-on: ubuntu-latest
    permissions:
      issues: read
    steps:
      - name: Debug event
        run: |
          echo "Event type: ${{ github.event_name }}"
          echo "Comment type: ${{ github.event.comment.node_id }}"
          echo "Event payload:"
          cat $GITHUB_EVENT_PATH

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Track Comments
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}

  review:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Code Review
        uses: ./
        with:
          gemini-api-key: ${{ secrets.GEMINI_API_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          max-diff-size: 500000
          model-name: gemini-1.5-flash
          custom-instructions: |
            Using bahasa indonesia,
            Extreme review.