name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List files
        run: |
          pwd
          echo "Direktori Action:"
          ls -la .
          echo "Isi review.py:"

      - name: Run Code Review
        uses: ./
        with:
          gemini-api-key: ${{ secrets.GEMINI_API_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          max-diff-size: 500000
          model-name: gemini-2.0-flash-thinking-exp-01-21
          custom-instructions: |
            Using bahasa indonesia,
            Extreme review.