name: Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Code Review
        uses: ./
        with:
          reviewer-api-key: ${{ secrets.REVIEWER_API_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          open-api-url: https://ollama.codeutsman.com/v1
          max-diff-size: 500000
          model-name: llama3.2
          custom-instructions: |
            Using bahasa indonesia,
            Extreme review.