name: Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Code Review
        uses: ./
        with:
          gemini-api-key: ${{ secrets.GEMINI_API_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          max-diff-size: 500000
          model-name: gemini-1.5-flash
          issue-number: ${{ github.event.issue.number }}
          custom-instructions: |
            Using bahasa indonesia,
            Extreme review.