name: Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug directory contents
        run: |
          pwd
          ls -la
          ls -la src/

      - name: Run Code Review
        uses: ./
        with:
          reviewer-api-key: ${{ secrets.REVIEWER_API_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          open-ai-url: https://generativelanguage.googleapis.com/v1beta/openai/
          max-diff-size: 500000
          model-name: deepseek-reasoner
          custom-instructions: |
            Using bahasa indonesia,
            Extreme review.