name: Test Issue Comment Trigger

on:
  pull_request_review_comment:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Comment
        run: |
          echo "new comment on : ${{ github.event.comment.body }}"
          
